# Generated by Django 4.0.5 on 2022-06-18 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
