# Generated by Django 4.0.5 on 2022-06-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_date_expired_alter_task_date_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_expired',
        ),
    ]
